src/Entity/C/xampp/htdocs/EdunetMain1/src/Entity/ComplaintGestion/ComplaintResponsePhp.php
<?php

namespace App\Entity\C\xampp\htdocs\EdunetMain1\src\Entity\ComplaintGestion;

use App\Repository\C\xampp\htdocs\EdunetMain1\src\Entity\ComplaintGestion\ComplaintResponsePhpRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ComplaintResponsePhpRepository::class)]
class ComplaintResponsePhp
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?bool $IsseenUser = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isIsseenUser(): ?bool
    {
        return $this->IsseenUser;
    }

    public function setIsseenUser(bool $IsseenUser): static
    {
        $this->IsseenUser = $IsseenUser;

        return $this;
    }
}

src/Entity/ComplaintGestion/Complaint.php
<?php

namespace App\Entity\ComplaintGestion;

use App\Entity\UserGestion\GlobalUser;
use App\Repository\UserGestion\GlobalUserRepository;

use App\Repository\ComplaintGestion\ComplaintRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ComplaintRepository::class)]
class Complaint
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'Complaints')]
    #[ORM\JoinColumn(nullable: true)]
    private ?GlobalUser $id_user = null;

    #[ORM\Column(type: 'datetime', nullable: true)]
    #[Assert\NotBlank(message:"Date of reclamation is required")]

    private ?\DateTimeInterface $date = null;




    #[ORM\Column(length: 10)]
    #[Assert\NotBlank(message:"Type is required")]

    private ?string $type = null;

    #[ORM\Column(length: 255)]

    private ?string $Description;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"")]

    private ?int $priority = null;

    #[ORM\OneToMany(mappedBy: 'id_Complaint', targetEntity:     ComplaintResponse::class, orphanRemoval: true)]
    private Collection $responses;

    public function __construct()
    {
        $this->responses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(int $priority): static
    {
        $this->priority = $priority;

        return $this;
    }

    public function getIdUser(): ?GlobalUser
    {
        return $this->id_user;
    }

    public function setIdUser(?GlobalUser $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    /**
     * @return Collection<int, Response>
     */
    public function getComplaintResponses(): Collection
    {
        return $this->responses;
    }

    public function addComplaintResponse(ComplaintResponse $response): static
    {
        if (!$this->responses->contains($response)) {
            $this->responses->add($response);
            $response->setIdComplaint($this);
        }

        return $this;
    }

    public function removeComplaintResponse(ComplaintResponse $response): static
    {
        if ($this->responses->removeElement($response)) {
            // set the owning side to null (unless already changed)
            if ($response->getIdComplaint() === $this) {
                $response->setIdComplaint(null);
            }
        }

        return $this;
    }

}

src/Entity/ComplaintGestion/ComplaintResponse.php
<?php

namespace App\Entity\ComplaintGestion;

use App\Repository\ComplaintGestion\ComplaintResponseRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ComplaintResponseRepository::class)]
class ComplaintResponse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    public function getId(): ?int
    {
        return $this->id;
    }
    #[ORM\Column(type: 'datetime', nullable: true)]
    #[Assert\NotBlank(message:"Date of reclamation is required")]

    private ?\DateTimeInterface $date = null;
  

    #[ORM\ManyToOne(inversedBy: 'ComplaintResponses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Complaint $id_Complaint = null;


    #[ORM\Column(length: 255)]

    private ?string $response = null;
    public function getResponse(): ?string
    {
        return $this->response;
    }

    public function setResponse(string $response): static
    {
        $this->response = $response;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    #[ORM\Column]
    private ?bool $seenByUser = false;

    
    public function isSeenByUser(): bool
    {
        return $this->seenByUser;
    }

    public function markAsSeenByUser(): void
    {
        $this->seenByUser = true;
    }
    
        public function setSeenByUser(bool $seenByUser): static
        {
            $this->seenByUser = $seenByUser;
    
            return $this;
        }
        public function getSeenByUser(): ?bool
        {
            return $this->seenByUser;
        }

    public function getIdComplaint(): ?Complaint
    {
        return $this->id_Complaint;
    }

    public function setIdComplaint(?Complaint $id_Complaint): static
    {
        $this->id_Complaint = $id_Complaint;

        return $this;
    }
    
}

templates/Complaint_gestion/Complaint.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edulance - Submit a Complaint</title>
    <!-- Favicons -->
    <link href="{{asset('assets/img/favicon.png')}}" rel="icon">
    <link href="{{asset('assets/img/logo.png')}}" rel="apple-touch-icon">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Froala Editor CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.1/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <!-- Custom Header CSS -->
    <link rel="stylesheet" href="{{asset('../components/header/header.css')}}">
    <!-- Vendor CSS Files -->
    <link href="{{asset('home/assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('home/assets/vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
    <link href="{{asset('home/assets/vendor/aos/aos.css')}}" rel="stylesheet">
    <link href="{{asset('home/assets/vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
    <link href="{{asset('home/assets/vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="{{asset('home/assets/css/main.css')}}" rel="stylesheet">
	    <style>
        /* Adjust the bottom margin of the form */
        .form-container {
            margin-bottom: 50px; /* Increase this value to increase the distance */
        }

        /* Or adjust the padding of the container */
        .container {
            padding-bottom: 120px; /* Increase this value to increase the distance */
        }
    </style>
</head>
<body>
    <!-- Header/Navigation Section -->
    <nav class="navbar">
        <div class="navbar-left">
            <a href="{{ path('home', {'id': id}) }}" class="logo"><img src="{{ asset('components/header/images/logo.png') }}" alt="logo"></a>
            <div class="search-box">
                <img src="{{asset('components/header/images/search.png')}}">
                <input type="text" placeholder="Search for anything">
            </div>
        </div>
       <div class="navbar-center">
    <ul>
        <li>
            <a href="{{ path('home', {'id': id}) }}" class="active-link">
                <img src="{{asset('components/header/images/home.png')}}" alt="home">
                <span>Home</span>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="{{asset('components/header/images/jobs.png')}}" alt="jobs">
                <span>Jobs</span>
            </a>
        </li>
        <li>
            <a href="{{path('menu_course')}}">
                <img src="{{asset('components/header/images/network.png')}}" alt="network">
                <span>Courses</span>
            </a>
        </li>
        <li>
            <a href="{{ path('complaint', {'id': id }) }}">
                <img src="{{ asset('components/header/images/network.png') }}" alt="network">
                <span>Add Complaints</span>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="{{asset('components/header/images/notification.png')}}" alt="notification">
                <span>Notifications</span>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="{{asset('components/header/images/notification.png')}}" alt="notification">
                <span>Team</span>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="{{asset('components/header/images/notification.png')}}" alt="notification">
                <span>Contact</span>
            </a>
        </li>
    </ul>
</div>

        <div class="navbar-right">
            <div class="online">
                {% if User is defined %}
                    {% if User > 0 %}
                        <img src="{{asset('components/header/images/user-1.png')}}" class="nav-profile-img" onclick="toggleMenu()">
                    {% else %}
                        <div class="order-3 flex gap-x-1 justify-end min-w-[100px] flex-nowrap flex-shrink-0 babybear:flex-wrap flex-2">
                            <a class="btn btn-light" href="https://www.linkedin.com/signup?trk=guest_homepage-basic_nav-header-join" data-tracking-control-name="guest_homepage-basic_nav-header-join" data-tracking-will-navigate="">
                                Join now
                            </a>
                            <a class="btn btn-primary" href="https://www.linkedin.com/login?fromSignIn=true&amp;trk=guest_homepage-basic_nav-header-signin" data-tracking-control-name="guest_homepage-basic_nav-header-signin" data-tracking-will-navigate="">
                                Sign in
                            </a>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </nav>

    <!-- Complaint Form Section -->
    <div class="container mt-5 form-container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card shadow">
                    <div class="card-body">
                        <h2 class="text-center mb-4">Submit a Complaint</h2>
                        <!-- Complaint Form -->
                        		{{ form_start(form, { 'action': path('complaint', {'id': id}), 'method': 'POST', 'attr': {'novalidate': 'novalidate'} }) }}

<div class="mb-3">
    {{ form_row(form.type, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="mb-3" id="editor">
    <textarea id="editor" name="{{ form.description.vars.full_name }}" class="form-control">{{ form.description.vars.value }}</textarea>
</div>

<div class="mb-3">
    {{ form_row(form.priority, {'attr': {'class': 'form-select'}}) }}
</div>

<div class="d-grid">
    {{ form_row(form.save, { 'label': 'Submit', 'attr': {'class': 'btn btn-primary btn-block'}}) }}
</div>

{{ form_end(form) }}
                        <!-- End of Complaint Form -->
                        <a href="{{ path('home', {'id': id}) }}" class="btn btn-secondary btn-block mt-3">Back to Home Page</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
 <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-5 col-md-12 footer-info">
          <a href="index.html" class="logo d-flex align-items-center">
            <span>EduLance</span>
          </a>
          <p>For more Informations:</p>
          <div class="social-links d-flex mt-4">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><a href="#">Web Design</a></li>
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Product Management</a></li>
            <li><a href="#">Marketing</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
          <h4>Contact Us</h4>
          <p>
            A108 Adam Street <br>
            New York, NY 535022<br>
            United States <br><br>
            <strong>Phone:</strong> +1 5589 55488 55<br>
            <strong>Email:</strong> info@example.com<br>
          </p>

        </div>
        

      </div>
    </div>

    <div class="container mt-4">
      <div class="copyright">
        &copy; Copyright <strong><span>Impact</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/impact-bootstrap-business-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">EduLance</a>
      </div>
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->
    <!-- Bootstrap Bundle JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Froala Editor JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.1/js/froala_editor.pkgd.min.js"></script>
    <script>
        var editor = new FroalaEditor('#editor');
    </script>
</body>
 
 </body>

</html>

templates/Complaint_gestion/list.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edulance - Submit a Complaint</title>
    <!-- Favicons -->
    <link href="{{asset('assets/img/favicon.png')}}" rel="icon">
    <link href="{{asset('assets/img/logo.png')}}" rel="apple-touch-icon">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Froala Editor CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.1/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <!-- Custom Header CSS -->
    <link rel="stylesheet" href="{{asset('../components/header/header.css')}}">
    <!-- Vendor CSS Files -->
    <link href="{{asset('home/assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('home/assets/vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
    <link href="{{asset('home/assets/vendor/aos/aos.css')}}" rel="stylesheet">
    <link href="{{asset('home/assets/vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
    <link href="{{asset('home/assets/vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="{{asset('home/assets/css/main.css')}}" rel="stylesheet">
    <style>
        /* Add your custom CSS styles here */
        /* Adjust the padding to match the spacing of other sections */
        .container {
            padding: 80px 0;
        }

      /* Style for the table */
/* Style for the table */
.table {
    width: 100%;
    margin-bottom: 1rem;
    color: #212529;
    border-collapse: separate; /* Separate borders */
    border-spacing: 0 8px; /* Adjust spacing between rows */
}

.table th,
.table td {
    padding: 0.75rem;
    vertical-align: top;
    border: none; /* Remove borders for table cells */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Add shadow */
}

.table thead th {
    vertical-align: bottom;
    border-bottom: 2px solid #dee2e6;
}

/* Style for action buttons */
.btn {
    padding: 0.5rem 1rem; /* Adjust button padding */
    font-size: 1rem;
    line-height: 1.5;
    border-radius: 0.25rem;
    border: none; /* Remove button borders */
}

.btn-edit {
    background-color: #0d6efd;
    color: #fff;
}

.btn-delete {
    background-color: #dc3545;
    color: #fff;
}

.btn-back {
    background-color: #6c757d;
    color: #fff;
}

.btn-actions {
    background-color: #198754;
    color: #fff;
}

.btn:hover {
    text-decoration: none;
}

.text-center {
    text-align: center;
}
/* Style for the status */
.status {
    display: inline-block;
    padding: 0.25rem 0.5rem;
    border-radius: 1rem; /* Adjust border radius as needed */
    background-color: #6cbf73; /* Background color for "Sent successfully" */
    color: #fff;
        text-align: center; /* Center text */
    justify-content: center; /* Center horizontally */

}

/* Additional styles for other statuses */
.status.pending {
    background-color: #fca130; /* Background color for "Pending" */
}

.status.resolved {
    background-color: #007bff; /* Background color for "Resolved" */
}

.status.in-progress {
    background-color: #ffc107; /* Background color for "In Progress" */
}


    </style>
</head>
<body>
 <!-- Header/Navigation Section -->
    <nav class="navbar">
        <div class="navbar-left">
            <a href="{{ path('home', {'id': id}) }}" class="logo"><img src="{{ asset('components/header/images/logo.png') }}" alt="logo"></a>
            <div class="search-box">
                <img src="{{asset('components/header/images/search.png')}}">
                <input type="text" placeholder="Search for anything">
            </div>
        </div>
       <div class="navbar-center">
    <ul>
        <li>
            <a href="{{ path('home', {'id': id}) }}" class="active-link">
                <img src="{{asset('components/header/images/home.png')}}" alt="home">
                <span>Home</span>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="{{asset('components/header/images/jobs.png')}}" alt="jobs">
                <span>Jobs</span>
            </a>
        </li>
        <li>
            <a href="{{path('menu_course')}}">
                <img src="{{asset('components/header/images/network.png')}}" alt="network">
                <span>Courses</span>
            </a>
        </li>
        <li>
            <a href="{{ path('complaint', {'id': id }) }}">
                <img src="{{ asset('components/header/images/network.png') }}" alt="network">
                <span>Add Complaints</span>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="{{asset('components/header/images/notification.png')}}" alt="notification">
                <span>Notifications</span>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="{{asset('components/header/images/notification.png')}}" alt="notification">
                <span>Team</span>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="{{asset('components/header/images/notification.png')}}" alt="notification">
                <span>Contact</span>
            </a>
        </li>
    </ul>
</div>

        <div class="navbar-right">
            <div class="online">
                {% if User is defined %}
                    {% if User > 0 %}
                        <img src="{{asset('components/header/images/user-1.png')}}" class="nav-profile-img" onclick="toggleMenu()">
                    {% else %}
                        <div class="order-3 flex gap-x-1 justify-end min-w-[100px] flex-nowrap flex-shrink-0 babybear:flex-wrap flex-2">
                            <a class="btn btn-light" href="https://www.linkedin.com/signup?trk=guest_homepage-basic_nav-header-join" data-tracking-control-name="guest_homepage-basic_nav-header-join" data-tracking-will-navigate="">
                                Join now
                            </a>
                            <a class="btn btn-primary" href="https://www.linkedin.com/login?fromSignIn=true&amp;trk=guest_homepage-basic_nav-header-signin" data-tracking-control-name="guest_homepage-basic_nav-header-signin" data-tracking-will-navigate="">
                                Sign in
                            </a>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="background"></div>
  

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <h2 class="text-center mb-4">List of Complaints</h2>

            
            <div class="form-group">
                <label for="typeFilter">Filter by Type:</label>
                <select id="typeFilter" class="form-control">
                    <option value="all">All</option>
                    <option value="technical">Technical</option>
                    <option value="conflict">Conflict</option>
                </select>
            </div>



            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Description</th>
                            <th>Priority</th>
                            <th>Date</th>
                            <th>Status</th>
                            <th class="actions-column">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
   {% for complaint in complaints %}
    <tr class="complaint-row {{ complaint.type }}">
        <td>{{ complaint.type }}</td>
        <td>{{ complaint.description }}</td>
        <td>{{ complaint.priority }}</td>
        <td>{{ complaint.date|date('Y-m-d H:i:s') }}</td>
        <td>
            {% if complaint.complaintResponses.isEmpty() %}
                <span class="status sent">Sent</span>
            {% else %}
                <span class="status resolved">Resolved</span>
            {% endif %}
        </td>
        <td class="actions-column">
            <a href="{{ path('complaint_edit', {'id': id, 'complaintId': complaint.id}) }}" class="btn btn-edit">
                <i class="bi bi-pencil-fill"></i>
            </a>
            <a href="{{ path('complaint_delete', {'id': id, 'complaintId': complaint.id}) }}" class="btn btn-delete">
                <i class="bi bi-trash-fill"></i>
            </a>
            <a href="{{ path('complaint_response', {'complaintId': complaint.id}) }}" class="btn btn-actions">
                <i class="bi bi-chat-fill">View Response</i>
            </a>
        </td>
    </tr>
{% endfor %}

</tbody>
>
                </table>
            </div>
            <div class="text-center">
                <a href="{{ path('home', {'id': id}) }}" class="btn btn-back">Back to Complaint Form</a>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        document.getElementById('typeFilter').addEventListener('change', function () {
            var selectedType = this.value;
            var complaintRows = document.querySelectorAll('.complaint-row');
            complaintRows.forEach(function (row) {
                if (selectedType === 'all' || row.classList.contains(selectedType)) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        });
    });
</script>

<!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-5 col-md-12 footer-info">
          <a href="index.html" class="logo d-flex align-items-center">
            <span>EduLance</span>
          </a>
          <p>For more Informations:</p>
          <div class="social-links d-flex mt-4">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><a href="#">Web Design</a></li>
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Product Management</a></li>
            <li><a href="#">Marketing</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
          <h4>Contact Us</h4>
          <p>
            A108 Adam Street <br>
            New York, NY 535022<br>
            United States <br><br>
            <strong>Phone:</strong> +1 5589 55488 55<br>
            <strong>Email:</strong> info@example.com<br>
          </p>

        </div>
        

      </div>
    </div>

    <div class="container mt-4">
      <div class="copyright">
        &copy; Copyright <strong><span>Impact</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/impact-bootstrap-business-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">EduLance</a>
      </div>
    </div>

  </footer><!-- End Footer -->

  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
   
</body>
</html>